### PR TITLE
Extend Time validation to support time with seconds and milliseconds.

### LINKED ISSUE #15: Time validation fails for Time string with seconds and milliseconds.
If element `E_0337()` has value like `083032` then validation fails because TryParseExact has format only for time without seconds and milliseconds.

### PR DESCRIPTION
**Pull request by sayfulloev**
Resolves #15 plus slightly reorganize DataElementValidator, split optional date time test to be Date and Time tests, add new mandatory datetime test.

### CODE REVIEW

File: EdiEngine/Validation/DataElementValidator.cs [hunk 1]
```diff
@@ -48,33 +44,100 @@ public static bool IsValid(this EdiSimpleDataElement el, MapSimpleDataElement de
...
+                    return el.Val.IsValidDateTimeString("HHmmssf");
+                case 8:
+                    return el.Val.IsValidDateTimeString("HHmmssff");
+                default:
+                    throw new NotSupportedException($"Time validation with length {el.Val.Length} is not implemented. {el.Type}");
+            }
+        }
+
+        private static bool IsValidDateTimeString(this string dateTime, string format)
+        {
```
Comment (olmelabs) [inline EdiEngine/Validation/DataElementValidator.cs]: Hi Sharif, 
Can you change it so it compiles in C# 6 and VS 2015 - as i am maintaining compatibility.

        private static bool IsValidDateTimeString(this string dateTime, string format)
        {
           DateTime dummyDt;
            return DateTime.TryParseExact(dateTime, format, CultureInfo.InvariantCulture, DateTimeStyles.None, out dummyDt);
        }

Comment (sayfulloev) [reply EdiEngine/Validation/DataElementValidator.cs]: Fixed!
